---
configure_keyboard: true
initial_key_repeat: 20 # 300ms
key_repeat: 1 # 15ms

configure_finder: true

configure_homebrew: true
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - hashicorp/tap
homebrew_formulae:
  - ansible
  - asciinema
  - asdf
  - azure-cli
  - bat
  - bfg
  - cmake
  - cowsay
  - exa
  - ffmpeg
  - fzf
  - gh
  - git
  - git-lfs
  - hashicorp/tap/terraform
  - hyperkit
  - imagemagick
  - jq
  - lazydocker
  - mas
  - minikube
  - neovim
  - nmap
  - yt-dlp
  - zsh
homebrew_casks:
  - aldente
  - altserver
  - apparency
  - appcleaner
  - balenaetcher
  - binance
  - blackhole-16ch
  - brave-browser
  - charles
  - chromedriver
  - datagrip
  - discord
  - docker
  - firefox
  - font-fira-code
  - font-meslo-lg-nerd-font
  - gfxcardstatus
  - github
  - google-chrome
  - iina
  - insomnia
  - iterm2
  - karabiner-elements
  - keyboardcleantool
  - logitech-g-hub
  - microsoft-auto-update
  - microsoft-office
  - microsoft-teams
  - ngrok
  - notion
  - openinterminal
  - openvpn-connect
  - parallels
  - parsec
  - pycharm
  - qbittorrent
  - qlcolorcode
  - qlimagesize
  - qlmarkdown
  - qlstephen
  - qlvideo
  - quicklook-json
  - quicklookase
  - raycast
  - rectangle
  - send-anywhere
  - slack
  - suspicious-package
  - visual-studio-code
  - vlc
  - wireshark
  - zoom

configure_mas: true
mas_apps:
  - 1440147259  # AdGuard for Safari
  - 497799835   # Xcode
  - 1333542190  # 1Password 7
  - 1295203466  # Microsoft Remote Desktop
  - 1364038646  # Right Click
  - 1265704574  # Bandizip
  - 416746898   # Hancom Office HWP 2014 VP Viewer
  - 869223134   # KakaoTalk
  - 747648890   # Telegram
  - 937984704   # Amphetamine
  - 458887729   # Translate Tab
  - 409203825   # Numbers

configure_zsh: true
antigen_url: https://raw.githubusercontent.com/zsh-users/antigen/master/bin/antigen.zsh
antigen_dest: ~/.antigen/antigen.zsh
antigen_plugins:
  - asdf
  - command-not-found
  - docker-compose
  - docker
  - fzf
  - git
  - gitignore
  - python
  - terraform
  - zsh-users/zsh-autosuggestions
  - zsh-users/zsh-completions
  - zsh-users/zsh-syntax-highlighting

configure_karabiner: true
