---
configure_keyboard: true
initial_key_repeat: 20  # 300ms
key_repeat: 1  # 15ms

configure_trackpad: true

configure_menubar: true

configure_dock: true
# Recommended to the multiples of 16
dock_size: 48
dock_magnification: true
dock_magnification_size: 80

configure_finder: true

configure_homebrew: true
homebrew_taps:
  - bufbuild/buf
  - hashicorp/tap
homebrew_formulae:
  - name: asciinema
  - name: asdf
  - name: azure-cli
  - name: bat
  - name: bfg
  - name: bufbuild/buf/buf
  - name: cmake
  - name: dive
  - name: eza
  - name: ffmpeg
  - name: fzf
  - name: gh
  - name: git
  - name: git-delta
  - name: git-lfs
  - name: hashicorp/tap/packer
  - name: hashicorp/tap/terraform
  - name: hashicorp/tap/vault
  - name: helix
  - name: helm
  - name: hugo
  - name: imagemagick
  - name: iperf3
  - name: jq
  - name: kubernetes-cli
  - name: lazydocker
  - name: mas
  - name: minikube
  - name: monolith
  - name: neovim
  - name: nmap
  - name: pipx
  - name: protobuf
  - name: ranger
  - name: ripgrep
  - name: rsync
  - name: yamllint
  - name: yt-dlp
  - name: zoxide
  - name: zsh
homebrew_casks:
  - name: aldente
  - name: apparency
  - name: appcleaner
  - name: balenaetcher
  - name: blackhole-16ch
  - name: brave-browser
  - name: charles
  - name: chromedriver
    install_options: [no-quarantine]
  - name: cyberduck
  - name: deepl
  - name: devtoys
  - name: discord
  - name: docker
  - name: firefox
  - name: font-fira-code
  - name: font-meslo-lg-nerd-font
  - name: google-chrome
  - name: gureumkim
  - name: heynote
  - name: hiddenbar
  - name: iina
  - name: insomnia
  - name: intellij-idea
  - name: iterm2
  - name: karabiner-elements
  - name: keyboardcleantool
  - name: microsoft-office
  - name: microsoft-teams
  - name: mac-mouse-fix
  - name: ngrok
  - name: notion
  - name: openinterminal
  - name: openvpn-connect
  - name: parallels
  - name: parsec
  - name: postman
  - name: qbittorrent
  - name: qlmarkdown
  - name: qlvideo
  - name: raycast
  - name: redisinsight
  - name: send-anywhere
  - name: slack
  - name: suspicious-package
  - name: syntax-highlight
    install_options: [no-quarantine]
  - name: tailscale
  - name: visual-studio-code
  - name: warp
  - name: wireshark
  - name: xquartz
  - name: zoom

configure_mas: true
mas_apps:
  - 1440147259  # AdGuard for Safari
  - 497799835   # Xcode
  - 1333542190  # 1Password 7
  - 1295203466  # Microsoft Remote Desktop
  - 1364038646  # Right Click
  - 1265704574  # Bandizip
  - 1463298887  # Userscripts-Mac-App
  - 416746898   # Hancom Office HWP 2014 VP Viewer
  - 869223134   # KakaoTalk
  - 747648890   # Telegram
  - 937984704   # Amphetamine
  - 458887729   # Translate Tab
  - 409203825   # Numbers

configure_karabiner: true
