---
configure_keyboard: true
initial_key_repeat: 20  # 300ms
key_repeat: 1  # 15ms

configure_trackpad: true

configure_menubar: true

configure_dock: true
# Recommended to the multiples of 16
dock_size: 48
dock_magnification: true
dock_magnification_size: 80

configure_finder: true

configure_homebrew: true
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - hashicorp/tap
homebrew_formulae:
  # - ansible
  - ansible-lint
  - asciinema
  - asdf
  - azure-cli
  - bat
  - bfg
  - cmake
  - cowsay
  - exa
  - ffmpeg
  - fzf
  - gh
  - git
  - git-delta
  - git-lfs
  - hashicorp/tap/terraform
  - hashicorp/tap/vault
  - helix
  - httpie
  - hugo
  - imagemagick
  - jq
  - kubernetes-cli
  - lazydocker
  # - libpq
  - mas
  - minikube
  # - neovim
  - nmap
  - pipx
  - protobuf
  - rsync
  - yamllint
  - yt-dlp
  - zoxide
  - zsh
homebrew_casks:
  - aldente
  - apparency
  - appcleaner
  - balenaetcher
  - binance
  - blackhole-16ch
  - brave-browser
  - charles
  - chromedriver
  - devtoys
  - discord
  - docker
  - firefox
  - font-fira-code
  - font-meslo-lg-nerd-font
  - google-chrome
  - gureumkim
  - iina
  - insomnia
  - intellij-idea
  - iterm2
  - karabiner-elements
  - keyboardcleantool
  - microsoft-office
  - microsoft-teams
  - mouse-fix
  - ngrok
  - notion
  - openinterminal
  - openvpn-connect
  - parallels
  - parsec
  - qbittorrent
  - qlmarkdown
  - qlstephen
  - qlvideo
  - quicklook-json
  - raycast
  - rectangle
  - redisinsight
  - send-anywhere
  - slack
  - suspicious-package
  - visual-studio-code
  - vlc
  - warp
  - wireshark
  - zoom

configure_mas: true
mas_apps:
  - 1440147259  # AdGuard for Safari
  - 497799835   # Xcode
  - 1333542190  # 1Password 7
  - 1295203466  # Microsoft Remote Desktop
  - 1364038646  # Right Click
  - 1265704574  # Bandizip
  - 416746898   # Hancom Office HWP 2014 VP Viewer
  - 869223134   # KakaoTalk
  - 747648890   # Telegram
  - 937984704   # Amphetamine
  - 458887729   # Translate Tab
  - 409203825   # Numbers

configure_karabiner: true
