---
- hosts: all

  vars_files:
    - default.config.yml

  gather_facts: false

  pre_tasks:
    - name: Include playbook configuration.
      ansible.builtin.include_vars: "{{ item }}"
      loop: "{{ lookup('ansible.builtin.fileglob', 'config.yml') }}"
      tags: always

  tasks:
    - import_tasks: tasks/keyboard.yml
      when: configure_keyboard
      tags: keyboard

    - import_tasks: tasks/finder.yml
      when: configure_finder
      tags: finder

    - import_tasks: tasks/homebrew.yml
      when: configure_homebrew
      tags: homebrew

    - import_tasks: tasks/mas.yml
      when: configure_mas
      tags: mas

    - import_tasks: tasks/zsh.yml
      when: configure_zsh
      tags: zsh

    - import_tasks: tasks/karabiner.yml
      when: configure_karabiner
      tags: karabiner

    - block:
        - name: Run configured post-provision ansible task files.
          ansible.builtin.include_tasks: "{{ outer_item }}"
          loop: "{{ query('fileglob', 'post_tasks/*.yml') | sort }}"
          loop_control:
            loop_var: outer_item
      tags: post
