---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  gather_facts: false

  pre_tasks:
    - name: Include playbook configuration.
      ansible.builtin.include_vars: "{{ item }}"
      loop: "{{ lookup('ansible.builtin.fileglob', 'config.yml') }}"
      tags: always

  tasks:
    - ansible.builtin.import_tasks: tasks/keyboard.yml
      when: configure_keyboard
      tags: keyboard

    - ansible.builtin.import_tasks: tasks/menubar.yml
      when: configure_menubar
      tags: menubar

    - ansible.builtin.import_tasks: tasks/dock.yml
      when: configure_dock
      tags: dock

    - ansible.builtin.import_tasks: tasks/finder.yml
      when: configure_finder
      tags: finder

    - ansible.builtin.import_tasks: tasks/homebrew.yml
      when: configure_homebrew
      tags: homebrew

    - ansible.builtin.import_tasks: tasks/mas.yml
      when: configure_mas
      tags: mas

    - ansible.builtin.import_tasks: tasks/karabiner.yml
      when: configure_karabiner
      tags: karabiner

    - name: Run post-provision task files in a block.
      tags: post
      block:
        - name: Run configured post-provision ansible task files.
          ansible.builtin.include_tasks: "{{ outer_item }}"
          loop: "{{ query('fileglob', 'post_tasks/*.yml') | sort }}"
          loop_control:
            loop_var: outer_item
