---
- hosts: all

  vars_files:
    - config.yml

  gather_facts: false

  tasks:
    - import_tasks: tasks/keyboard.yml
      when: configure_keyboard
      tags: keyboard

    - import_tasks: tasks/finder.yml
      when: configure_finder
      tags: finder

    - import_tasks: tasks/zsh.yml
      when: configure_zsh
      tags: zsh

    - import_tasks: tasks/karabiner.yml
      when: configure_karabiner
      tags: karabiner
