---
- name: Configure the dock size.
  community.general.osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: "{{ dock_size }}"

- name: Configure dock magnification.
  block:
    - name: Set dock magnification flag.
      community.general.osx_defaults:
        domain: com.apple.dock
        key: magnification
        type: bool
        value: "{{ dock_magnification }}"

    - name: Set dock magnification size.
      community.general.osx_defaults:
        domain: com.apple.dock
        key: largesize
        type: float
        value: "{{ dock_magnification_size }}"
