---
- name: Prevent .DS_Store files on network drives.
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true

- name: Show all filename extensions.
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true

- name: New Finder windows show user's home directory.
  block:
    - name: Set new Finder windows to show user's home directory.
      community.general.osx_defaults:
        domain: com.apple.finder
        key: NewWindowTarget
        type: string
        value: PfHm

    - name: Set new Finder windows target path.
      community.general.osx_defaults:
        domain: com.apple.finder
        key: NewWindowTargetPath
        type: string
        value: "file://{{ lookup('env', 'HOME') }}/"

- name: Set the search path to the current folder.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: SCcf

- name: Show Path Bar.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true

- name: Show Status Bar.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true

- name: Show hard disks on the desktop.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: bool
    value: true

- name: Show external hard disks on the desktop.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: true

- name: Show removable media on the desktop.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: bool
    value: true

- name: Show mounted servers on the desktop.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    type: bool
    value: true

- name: Disable the warning when changing a file extension.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false

- name: Enable spring loading for directories.
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.springing.enabled
    type: bool
    value: true

- name: Remove the spring loading delay for directories.
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.springing.delay
    type: float
    value: '0.1'

- name: Use list view in all Finder windows by default.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: Nlsv  # Column: clmv, List: Nlsv, Gallery: glyv, Icon: icnv
