---
- name: Copy Karabiner-Elements complex modifications.
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: ~/.config/karabiner/assets/complex_modifications/
  loop: "{{ query('fileglob', 'Karabiner-Elements/*.json') }}"
