---
- name: Create .zshrc
  block:
    - name: Set default values
      ansible.builtin.set_fact:
        zshrc_custom: {}

    - name: Get custom script files.
      ansible.builtin.set_fact:
        zshrc_custom: "{{ zshrc_custom | combine({(item | basename): lookup('file', item)}) }}"
      loop: "{{ query('fileglob', 'assets/zsh/custom/*.zsh') }}"

    - name: Create .zshrc from template.
      ansible.builtin.template:
        src: assets/zsh/dotfiles/.zshrc.j2
        dest: ~/.zshrc

- name: Copy Powerlevel10k configuration file.
  ansible.builtin.copy:
    src: assets/zsh/dotfiles/.p10k.zsh
    dest: ~/.p10k.zsh
