---
name: CI

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install test dependencies.
        run: |
          pipx install ansible-lint
          pipx install yamllint
      - name: Lint code.
        run: |
          yamllint .
          ansible-lint
